language: c

jobs:
  include:
    ### cross builds on AMD64 ###

    - os: linux
      dist: focal
      env: BADGE=linux-mingw-64
      name: linux-mingw
      compiler: gcc-10
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages:
            ["gcc-10", "libusb-1.0.0-dev", "libgtk-3-dev", "rpm", "mingw-w64"]

    - os: linux
      dist: focal
      env: BADGE=linux-mingw-32
      name: linux-mingw
      compiler: gcc-10
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages:
            ["gcc-10", "libusb-1.0.0-dev", "libgtk-3-dev", "rpm", "mingw-w64"]

    ### macOS ###

    - os: osx
      env: BADGE=osx
      osx_image: xcode10.3 # xcode11.3 to xcode11.3.1 fail to compile
      name: macOS 10.14.4 gcc
      compiler: gcc
      addons:
        homebrew:
          packages:
            - gcc
            - libusb
            - gtk+3

    - os: osx
      env: BADGE=osx
      osx_image: xcode10.3 # xcode11.3 to xcode11.3.1 fail to compile
      name: macOS 10.14.4 gcc 32-bit
      compiler: gcc
      addons:
        homebrew:
          packages:
            - gcc
            - libusb
            - gtk+3
      before_install:
        - CFLAGS="$CFLAGS -m32"; CXXFLAGS="$CXXFLAGS -m32"; LDFLAGS="$LDFLAGS -m32";

    - os: osx
      env: BADGE=osx
      osx_image: xcode10.3 # xcode11.3 to xcode11.3.1 fail to compile
      name: macOS 10.14.4 clang
      compiler: clang
      addons:
        homebrew:
          packages:
            - clang
            - libusb
            - gtk+3

    - os: osx
      env: BADGE=osx
      osx_image: xcode10.3 # xcode11.3 to xcode11.3.1 fail to compile
      name: macOS 10.14.4 clang 32-bit
      compiler: clang
      addons:
        homebrew:
          packages:
            - clang
            - libusb
            - gtk+3
      before_install:
        - CFLAGS="$CFLAGS -m32"; CXXFLAGS="$CXXFLAGS -m32"; LDFLAGS="$LDFLAGS -m32";

    - os: osx
      env: BADGE=osx
      osx_image: xcode12.5
      name: macOS 11.3 gcc
      compiler: gcc
      addons:
        homebrew:
          packages:
            - gcc
            - libusb
            - gtk+3

    - os: osx
      env: BADGE=osx
      osx_image: xcode12.5
      name: macOS 11.3 clang
      compiler: clang
      addons:
        homebrew:
          packages:
            - clang
            - libusb
            - gtk+3

script:
  - git fetch --tags
  - printenv
  - cmake --version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] || [[ "$TRAVIS_OS_NAME" == "osx" ]];  then ./.travis.sh; fi
